---
title: "R Notebook"
output: html_notebook
---

```{r}
data("multi_model_dataset")
df = multi_model_dataset %>% filter(model_name == "Model 1")
```


```{r}
ci_data_list = function(obj){
data.frame(x = as.numeric(rownames(obj)),
                     lower = obj[, 1],
                     upper = obj[, 3])
}

ci_data = df %>% 
  dplyr::group_by(model_name) %>% 
  dplyr::group_nest() %>% 
  dplyr::mutate(roc = purrr::map(data, ~ pROC::roc_(data = ., response = "outcomes", predictor = "predictions", ci = TRUE, plot=FALSE)),
                roc = roc %>% setNames(model_name),
                ci_spec = purrr::map(roc, ~ pROC::ci.se(., specificities = seq(0, 1, l = 25))), 
                ci_ribbon = purrr::map(ci_spec, ~ ci_data_list(.)))
```


```{r}
g1 = pROC::ggroc(ci_data$roc) +
  ggplot2::theme_minimal() + 
  ggplot2::geom_abline(
    slope = 1,
    intercept = 1,
    linetype = "dashed",
    alpha = 0.7,
    color = "grey"
  ) +
  ggplot2::coord_equal() + 
  ggplot2::scale_color_brewer(name = 'name', palette = 'Set1') +
  ggplot2::scale_fill_brewer(name = 'name', palette = 'Set1')
```


```{r}
if(ci){
ribbon = ci_data %>% 
  dplyr::select(model_name, ci_ribbon) %>% 
  dplyr::rename(name = model_name) %>% 
  tidyr::unnest_wider(ci_ribbon) %>% 
  tidyr::unnest(cols = c(x, lower, upper))

# ci_values = ci_data %>% 
#   dplyr::select(model_name, roc) %>% 
#   dplyr::mutate(ci = purrr::map(roc, ~ .$ci)) %>% 
#   dplyr::select(-roc)

ci_values = ci_data %>% 
  dplyr::select(model_name, roc) %>% 
  dplyr::mutate(ci = purrr::map(roc, ~ pROC::ci(.))) 

g2 = g1 + ggplot2::geom_ribbon(data = ribbon,
                          ggplot2::aes(fill = name, x = x, ymin = lower, ymax = upper), 
                          alpha = 0.15, 
                          inherit.aes = FALSE)+
  ggplot2::guides(colour = "legend")
} else g2 + ggplot2::guides(colour = "legend")
g2
# ci.grob <-  gridExtra::tableGrob(ci_values$ci)#, gpar.coretext = gpar(col = "black", cex = 1))
```



